- Infrastructure:
    - Traefik:
        href: http://traefik.home
        description: Reverse proxy
        icon: traefik.png
        widget:
          type: traefik
          url: http://traefik:8080

    - Pi-hole:
        href: http://pihole.home/admin
        description: DNS and ad blocker
        icon: pi-hole.png
        widget:
          type: pihole
          url: http://pihole
          version: 6
          key: {{HOMEPAGE_VAR_PIHOLE_API_KEY}}
- Monitoring:
    - Grafana:
        href: http://grafana.home
        description: Metrics dashboard
        icon: grafana.png
        widget:
            type: grafana
            version: 2
            url: http://grafana:3000
            username: {{HOMEPAGE_VAR_GRAFANA_USER}}
            password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
    - Prometheus:
        href: http://prometheus.home
        description: Metrics collection
        icon: prometheus.png
        widget:
            type: prometheus
            url: http://prometheus:9090
- Media:
    - Nextcloud:
        href: http://nextcloud.home
        description: Cloud Storage
        icon: nextcloud.png
        widget:
            type: nextcloud
            url: {{HOMEPAGE_VAR_NEXTCLOUD_URL}}
            key: {{HOMEPAGE_VAR_NEXTCLOUD_TOKEN}}
            fields: ["cpuload", "memoryusage", "freespace"]
    - Grimmory:
        href: http://grimmory.home
        description: Library
        icon: booklore.png
    - Navidrome:
        href: http://navidrome.home
        description: Music
        icon: navidrome.png
        widget:
            type: navidrome
            url: {{HOMEPAGE_VAR_NAVIDROME_URL}}
            user: julio
            token: {{HOMEPAGE_VAR_NAVIDROME_TOKEN}}
            salt: {{HOMEPAGE_VAR_NAVIDROME_SALT}}
