- Infrastructure:
    - Traefik:
        href: http://traefik.home
        description: Reverse proxy
        icon: traefik.png
        widget:
          type: traefik
          url: http://traefik:8080

    - Pi-hole:
        href: http://pihole.home/admin
        description: DNS and ad blocker
        icon: pi-hole.png
        widget:
          type: pihole
          url: http://pihole
          version: 6
          key: {{HOMEPAGE_VAR_PIHOLE_API_KEY}}
- Monitoring:
    - Grafana:
        href: http://grafana.home
        description: Metrics dashboard
        icon: grafana.png
- Media:
    - Nextcloud:
        href: http://nextcloud.home
        description: Cloud Storage
        icon: nextcloud.png
        widget:
            type: nextcloud
            url: {{HOMEPAGE_VAR_NEXTCLOUD_URL}}
            key: {{HOMEPAGE_VAR_NEXTCLOUD_TOKEN}}
            fields: ["cpuload", "memoryusage", "freespace"]
    - Grimmory:
        href: http://grimmory.home
        description: Library
        icon: booklore.png
