global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'infra-vm'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          vm: 'infra'

  - job_name: 'media-vm'
    static_configs:
      - targets: ['192.168.1.72:9100']
        labels:
          vm: 'media'

  - job_name: 'games-vm'
    static_configs:
      - targets: ['192.168.1.68:9100']
        labels:
          vm: 'games'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'infra-containers'
    static_configs:
      - targets: ['cadvisor:8080']
        labels:
          vm: 'infra'

  - job_name: 'media-containers'
    static_configs:
      - targets: ['192.168.1.72:8085']
        labels:
          vm: 'media'

  - job_name: 'games-containers'
    static_configs:
      - targets: ['192.168.1.68:8085']
        labels:
          vm: 'games'

  - job_name: 'Proxmox-host'
    static_configs:
      - targets: ['192.168.1.69:9100']
        labels:
          vm: 'Proxmox-host'
    